### ISSUE TITLE
Instead of mocking, use schema only usage

### ISSUE THREAD

**Issue by benjie** [adwiens/postgraphile-node#1]
We have support for issuing GraphQL requests from a non-HTTP context, e.g. see: https://www.graphile.org/postgraphile/usage-schema/#calling-a-resolver-from-a-resolver; it may be better to leverage this API directly rather than mocking req/res.

**Comment by drewwiens** [comment]
Thanks for the tip! I'll keep that in mind for a future major version. Closing this for now since the current approach is functional.
